### ISSUE TITLE
你好，我最近正在读segmap的源码，想问问你在读这个源码的时候有没有其他的笔记

### ISSUE THREAD

**Issue by xujiagen** [HugueLiu/my_segmap#1]
请问你在读segmap的源码的时候有博客更新或者一些笔记吗？我读了segmap的源码有一周的，希望给点指点，谢谢，我的邮箱xjiagen@gmail.com.

**Comment by HugueLiu** [comment]
抱歉， 我最近在忙其他事，没怎么看代码了，也什么整理好的笔记。
